services:
  api:
    build:
      context: .
      dockerfile: src/Merchant.Todont.Web/Dockerfile
    environment:
      - ConnectionStrings__TodontContext=Host=postgres;Port=5432;Database=todont;Username=todont;Password=todont;
      - Jwt__Key=/run/secrets/jwt_key
    secrets:
      - jwt_key
    ports:
      - 5000
      - 5001
  postgres:
    image: postgres:alpine
    ports:
      - 5432
    environment:
      - POSTGRES_USER=todont
      - POSTGRES_PASSWORD=todont
      - POSTGRES_DB=todont
secrets:
  jwt_key:
    file: ./jwt_key.txt
      
      
