services:
  app:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
     - 80:5002
  api:
    build:
      context: .
      dockerfile: src/Merchant.Todos.Web/Dockerfile
    environment:
      - ConnectionStrings__TodontContext=Host=postgres;Port=5432;Database=todont;User=todont;Password=todont;
    ports:
      - 5000
      - 5001
  postgres:
    image: postgres:alpine
    ports:
      - 5432
    environment:
      - POSTGRES_USER=todont
      - POSTGRES_PASSWORD=todont
      - POSTGRES_DB=todont
      
      