services:
  api:
    build:
      context: .
      dockerfile: src/Merchant.Todont.Web/Dockerfile
    environment:
      - ConnectionStrings__TodontContext=Host=postgres;Port=5432;Database=todont;Username=todont;Password=todont;
      - Jwt__Key=/run/secrets/jwt_key
    secrets:
      - jwt_key
    ports:
      - 5008:80
      - 5009:443
    networks:
      - local
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=todont
      - POSTGRES_PASSWORD=todont
      - POSTGRES_DB=todont
    networks:
      - local
secrets:
  jwt_key:
    file: ./jwt_key.txt
networks:
  local:
    driver: bridge
      
